services:
  webserver:
    container_name: php-pmb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql-db
    networks:
      - pmb-tier

  mysql-db:
    container_name: mysql-pmb
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=pmb
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3308:3306"
    networks:
      - pmb-tier

  phpmyadmin:
    container_name: phpmyadmin-pmb
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - pmb-tier

networks:
  pmb-tier: